### ISSUE TITLE
clip ชื่อ member ให้เหลือไม่เกิน n ตัวอักษร

### ISSUE THREAD

**Issue by thananon** [narze/kuro#2]
ชื่อยาวเกินมีปัญหา โดยเฉพาะพี่วัว น่าจะมีให้ clip

`abcdefghijklmnop` -> `abcdefg..`

**Comment by narze** [comment]
![image](https://user-images.githubusercontent.com/248741/170310044-b78dcae0-87bd-488d-9302-f0f11bdcfa5f.png)
Clipped by length, if text longer than the div length it will be clipped with ellipsis
